### ISSUE TITLE
Fix `Downloads` page details for Windows build

### ISSUE THREAD

**Issue by Eagle3386** [xiph/flac-website#5]
While xiph/flac#113 was fixed a couple of months ago, the mentioned [Downloads](https://xiph.org/flac/download.html) page details for Windows were not updated:
https://github.com/xiph/flac-website/blob/30b96fff1ee9b3101dc1e7a118f0bed56cdc1ca4/download.html#L12

Currently, they still state (emphasis by me):
> Windows: FLAC for Windows (**command-line tools only**, the file flac-X.Y.Z-win.zip contains both 32 and 64 bit **binaries**).

Please update that information, too, e. g. like this:

> Windows: FLAC for Windows (the file flac-X.Y.Z-win.zip contains both command-line tools and libaries, in 32 and 64 bit).

I'll provide a PR for my suggestion in a minute…

**Comment by Eagle3386** [comment]
@erikd or @ktmf01 anything I can improve to get this rather small improvement merged?

**Comment by ktmf01** [comment]
I think the change is fine, but I don't have write access to this repository. You'll have to be patient for someone with write access to have a little spare time

**Comment by Eagle3386** [comment]
I see. GitHub told me you've contributed to this repo earlier which is why I concluded you've got said write access.

**Comment by Eagle3386** [comment]
Issue fixed (merged in GitLab, deployed to https://xiph.org/flac/download.html), hence closing.
